In [1]:
#welcome data analysis

In [2]:
###hi hello

In [8]:
## python
- introduction
- datatypes
- ds
- functions
- files

IndentationError: unexpected indent (<ipython-input-8-578ca28cf722>, line 3)

## python
- introduction
- datatypes
- ds
- functions
- files

 <img src="python.jpg">


## Numpy
 - numpy means numerical python
 - it works as data 
 - creating numpy array

In [6]:
import numpy as np

In [11]:
##creating numpy array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
a.size

5

In [9]:
a.shape

(5,)

In [22]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
a2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
import numpy as np
a2=np.random.rand(1,10)


In [19]:
np.random.randint(1,10)

9

In [3]:
import numpy as np 
a2=np.arange(1,100)
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
a3=a2.reshape(9,11)

In [6]:
a3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66],
       [67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77],
       [78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
       [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [7]:
a3[a3%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [21]:
a1=np.ones([3,5],int)

In [22]:
a2=np.zeros([3,5],int)

In [23]:
np.hstack((a1,a2))

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

In [25]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [26]:
np.linspace(1,50,200)

array([ 1.        ,  1.24623116,  1.49246231,  1.73869347,  1.98492462,
        2.23115578,  2.47738693,  2.72361809,  2.96984925,  3.2160804 ,
        3.46231156,  3.70854271,  3.95477387,  4.20100503,  4.44723618,
        4.69346734,  4.93969849,  5.18592965,  5.4321608 ,  5.67839196,
        5.92462312,  6.17085427,  6.41708543,  6.66331658,  6.90954774,
        7.15577889,  7.40201005,  7.64824121,  7.89447236,  8.14070352,
        8.38693467,  8.63316583,  8.87939698,  9.12562814,  9.3718593 ,
        9.61809045,  9.86432161, 10.11055276, 10.35678392, 10.60301508,
       10.84924623, 11.09547739, 11.34170854, 11.5879397 , 11.83417085,
       12.08040201, 12.32663317, 12.57286432, 12.81909548, 13.06532663,
       13.31155779, 13.55778894, 13.8040201 , 14.05025126, 14.29648241,
       14.54271357, 14.78894472, 15.03517588, 15.28140704, 15.52763819,
       15.77386935, 16.0201005 , 16.26633166, 16.51256281, 16.75879397,
       17.00502513, 17.25125628, 17.49748744, 17.74371859, 17.98

In [28]:
np.full(15,10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [29]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [30]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
a2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [36]:
np.hsplit(a2,5)

[array([[0],
        [0],
        [0]]),
 array([[0],
        [0],
        [0]]),
 array([[0],
        [0],
        [0]]),
 array([[0],
        [0],
        [0]]),
 array([[0],
        [0],
        [0]])]

In [45]:
a2=np.arange(1,31)

In [46]:
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [48]:
a2.sum()

465

In [52]:
a2.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [54]:
np.exp(np.arange(1,10))

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [55]:
a2.mean()

15.5

In [58]:
np.median(a2)

15.5

In [59]:
np.percentile(a2,5)

2.45

In [61]:
a5=a2.reshape(5,6)

In [62]:
a5

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [63]:
a5.T

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

In [66]:
np.sin(a5)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111, -0.99999021,
        -0.53657292],
       [ 0.42016704,  0.99060736,  0.65028784, -0.28790332, -0.96139749,
        -0.75098725],
       [ 0.14987721,  0.91294525,  0.83665564, -0.00885131, -0.8462204 ,
        -0.90557836],
       [-0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
        -0.98803162]])

In [67]:
np.sin(90)

0.8939966636005579

In [ ]:
np.